C#######################################################################
C
C     PURPOSE -
C
C        DEFINES variables used in command processing
C
C     CHANGE HISTORY -
C
C        $Log: commands_lg.h,v $
C        Revision 2.00  2007/11/03 00:49:10  spchu
C        Import to CVS
C
CPVCS    
CPVCS       Rev 1.1   Wed Aug 04 10:23:26 1999   dcg
CPVCS     allow more definitions and longer commands
CPVCS
CPVCS       Rev 1.1   Mon Feb 22 16:05:36 1999   dcg
CPVCS    change in syntax for sun
CPVCS
CPVCS       Rev 1.0   Mon Feb 22 15:04:58 1999   dcg
CPVCS    Initial revision.
C
C#######################################################################
C
C  last_char is the location of the last character in cmd_stack
c  len_buff is the length of cmd_buffer
c  len_cmd is the length of a single command
c  maxlen_stack is the maximum stack length
c
      integer last_char, len_buff, len_cmd, maxlen_stack,maxlen_buff,
     *  maxcmd_args,maxnlevels
      character*32 initname
      parameter (maxlen_buff=16384)
      parameter (maxnlevels=100)
      parameter (maxcmd_args=16384)
      common /ccommands_lg/ clevels, cmd_buff, cmd_temp,
     *   command,cline,error_msg,initname
      common /icommands_lg/ jlevels,nlevels,last_char,
     * len_buff, len_cmd, maxlen_stack
c
C nlevels is the number of recursion levels of command processing
C new levels are created by encountering 'infile' or 'input' commands
c or by the execution of 'dotasks'
C clevels(i) contains the name of the input file corresponding to
C  level i or 'interactive_lg' for interactive input or 'internal_lg'
C  for commands generated by a dotask
C
      integer nlevels , jlevels(maxnlevels)
      character*32 clevels(maxnlevels)
C
C  cmd_buffer is a the command buffer
C  cmd_temp is a scratch command work area
c  command is a holding area for a single command
c  cline is a holding area for one reading one line
c
      character*80 cline
      character*16384 cmd_buff, cmd_temp, command
      character*132 error_msg
      pointer (ipcmd_stack,cmd_stack)
      character*1000 cmd_stack
c
c  definition_name is the list of names defined via the 'define' command
c  definition_off is the offset into definitions to find the
c    string that should replace the occurance of definition_name
c  maxdefinitions is the maximum number of definitions allowed
C  ndefinitions is the number of definitions
c  lastchar_def is the last character in 'defintion'
c
      integer maxdefinitions,maxlen_def,ndefinitions,lastchar_def
      parameter (maxdefinitions=1000)
      integer definitions_off(1000)
      character*32 definitions_name(1000)
      common / idefines / ndefinitions,lastchar_def,definitions_off
      common / cdefines / definitions_name
      pointer (ipdefinition,definition)
      character*1000 definition
 
