<a name="navigation"></a>
<h6 id="barleft">EES Focus Areas</h6>

<ul id="nav">
  <li><a href="http://www.ees.lanl.gov/capabilities/atmosphere.shtml"><strong>Atmosphere and Ocean Science</strong></a></li>
  <li><a href="http://www.ees.lanl.gov/capabilities/computational.shtml"><strong>Computational Science</strong></a></li>
  <li><a href="http://www.ees.lanl.gov/capabilities/ecology.shtml"><strong>Ecology</strong></a></li>
  <li><a href="http://www.ees.lanl.gov/capabilities/geochem.shtml"><strong>Geochemistry and Geomaterials</strong></a></li>
  <li><a href="http://www.ees.lanl.gov/capabilities/geology.shtml"><strong>Geology</strong></a></li>
  <li><a href="http://www.ees.lanl.gov/capabilities/geophysics.shtml"><strong>Geophysics and Seismology</strong></a></li>
  <li><a href="http://www.ees.lanl.gov/capabilities/hydrology.shtml"><strong>Hydrology</strong></a></li>
  <li><a href="http://www.ees.lanl.gov/capabilities/techman.shtml"><strong>Technical Leadership</strong></a></li>
</ul>
