<h6 id="bar"><strong>LaGriT Links</strong></h6>

<ul class="ratext">
		
<li><a href="index.shtml">LaGriT Home Page</a></li>
 <li><a href="manual.shtml"><strong>On Line Manual</strong></a></li>
 <li><a href="features.shtml">Features</a></li>
 <li><a href="http://laws.lanl.gov/XCM/gmv/GMVHome.html">General Mesh Viewer (GMV)</a></li>
  <li><a href="applications.shtml">LaGriT Applications</a></li>
  <li><a href="development.shtml">LaGriT Code Development Team</a></li>
 <li><a href="pdfs/lagrit.pdf">LaGriT Facts (pdf)</a></li>
 <li><a href="graphics.shtml">LaGriT Graphics Examples</a></li>
  <li><a href="licensing.shtml">LaGriT Licensing</a></li>
  <li><a href="publications.shtml">LaGriT Publications</a></li>
<li><a href="release.shtml">Release Notes</a></li>

</ul>

<ul id="nav">
 <li><a href="mailto:lagrit-reg@lanl.gov"><strong>Contact LaGriT</strong></a></li>
</ul>

<form action="http://searcher-green.lanl.gov/search">
       <input type="text" name="q" columns="18" maxlength="255" value="" />             
	   <input type="submit" name="btnG" value="Search LaGriT Site" />
       <input type="hidden" name="client" value="outside_lanl" />
       <input type="hidden" name="proxyreload" value="1" />              
	   <input type="hidden" name="proxystylesheet" value="outside_lanl" />
       <input type="hidden" name="site" value="lagrit" />             
	   <input type="hidden" name="output" value="xml_no_dtd" />
</form>

<form action="http://searcher-green.lanl.gov/search">
      <input type="text" name="q" columns="18" maxlength="255" value="">
      <input type="submit" name="btnG" value="Search Online Manual">
      <input type="hidden" name="client" value="outside_lanl">
      <input type="hidden" name="proxyreload" value="1" />
      <input type="hidden" name="proxystylesheet" value="outside_lanl">
      <input type="hidden" name="site" value="lagrit_docs">
      <input type="hidden" name="output" value="xml_no_dtd">
</form>

