

<a name="toolbar"></a>
<div id="toolbar">
  <ul>
    <li><a id="" href="http://www.ees.lanl.gov/index.shtml">EES Home</a></li>
<!--#include virtual="/includes/ees_internal.shtml" -->
<!--#if expr="${in_ees} = true" -->
<li><a id="internal"href="http://int.ees.lanl.gov">EES Internal</a></li>
<!--#endif -->
 <li><a id="" href="/index.shtml">LaGriT Home</a></li>

	
  </ul> 
</div>



